apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: broker-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: broker
    spec:
      containers:
      - name: broker
        image: kaptaind/broker
        ports:
        - containerPort: 3000